### ISSUE TITLE
Logical bug in setQueryParameter(URLEncoder, String, Object)

### ISSUE THREAD

**Issue by ndawod** [moznion/uribuilder-tiny#4]
There's a `queryParameters.clear();` line there which I believe is just a copy-paste error; this method should not clear the query parameters map but only append to it.

https://github.com/moznion/uribuilder-tiny/blob/cbbbbac8c8e7d4724da117ddad3be916f9b4627a/src/main/java/net/moznion/uribuildertiny/URIBuilderTiny.java#L328

**Comment by moznion** [comment]
Thank you for reporting. I'll investigate that.

**Comment by moznion** [comment]
@ndawod
I guess this is not a bug, this is expected behavior.
I've forgotten the exact version of the [URIBuilder of the Apache HTTP Client](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html), but that library provides a setter-method to replace query parameter entirely (FYI, the latest URIBuilder doesn't act like that, that appends parameter(s)). IIRC, it respected to implement this `setQueryParameter()` method according to the behavior of that.
If you would like to append the query parameter, please use `URIBuilderTiny#addQueryParameters()` or `URIBuilderTiny#addQueryParameters()` instead of the setter.

**Comment by moznion** [comment]
If you have other questions, please feel free to reopen this issue or create another one.
